In [5]:
import numpy as np
import pandas as pd

In [6]:
grad=pd.read_csv('/content/drive/MyDrive/ProfProj/GRAD.csv')
tab2=pd.read_csv('/content/drive/MyDrive/ProfProj/tab2.csv')
tab3=pd.read_csv('/content/drive/MyDrive/ProfProj/tab3.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,30,31,33,34,35,36,37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
for i in range(len(grad)):
  x=grad.iloc[i,0]
  if(x!='-----'):
    y=float(x)
  else:
    y =float('nan')
  grad.iloc[i,0]=y

grad=grad.groupby('INDEX').get_group(42101)

In [8]:
for i in range(len(grad)):
  x=grad.iloc[i,1]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,1]=y
  x=grad.iloc[i,2]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,2]=y
  x=grad.iloc[i,3]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,3]=y
  x=grad.iloc[i,20]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,20]=y
  x=grad.iloc[i,21]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,21]=y
  x=grad.iloc[i,22]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,22]=y
  x=grad.iloc[i,23]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,23]=y
  x=grad.iloc[i,24]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  grad.iloc[i,24]=y

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [9]:
Radiations=grad[['YEAR','MN','DT','DTRAD','BHSS','W1','T1','T2']]
Radiations['T']=grad['T2']-grad['T1']
Radiations=Radiations.drop(['T1','T2'],axis=1)
Radiations.isnull().sum()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

YEAR        0
MN          0
DT          0
DTRAD    1138
BHSS      957
W1        517
T         517
dtype: int64

In [10]:
# for i in range(len(Radiations)):
#   x=Radiations.iloc[i,5]
#   if(x==1.0):
#     Radiations.iloc[i,5]='BLUE SKY'
#   elif(x==2.0):
#     Radiations.iloc[i,5]='CLOUDY WEATHER'
#   elif(x==3.0):
#     Radiations.iloc[i,5]='OVERCAST SKY'
#   elif(x==4.0):
#     Radiations.iloc[i,5]='SQUALL'
#   elif(x==5.0):
#     Radiations.iloc[i,5]='RAIN'
#   elif(x==6.0):
#     Radiations.iloc[i,5]='PASSING SHOWERS'
#   elif(x==7.0):
#     Radiations.iloc[i,5]='DRIZZLE'
#   elif(x==8.0):
#     Radiations.iloc[i,5]='SNOW'
#   elif(x==9.0):
#     Radiations.iloc[i,5]='HAIL'
#   elif(x==10.0):
#     Radiations.iloc[i,5]='THUNDER'
#   elif(x==11.0):
#     Radiations.iloc[i,5]='DISTANT LIGHTENING'
#   elif(x==12.0):
#     Radiations.iloc[i,5]='FOG'
#   elif(x==13.0):
#     Radiations.iloc[i,5]='HAZE'
#   else:
#     Radiations.iloc[i,5]='MIST'

In [11]:
!pip install fancyimpute
from fancyimpute import IterativeImputer

Collecting fancyimpute
  Downloading fancyimpute-0.7.0.tar.gz (25 kB)
Collecting knnimpute>=0.1.0
  Downloading knnimpute-0.1.0.tar.gz (8.3 kB)
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (1.0.2)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (1.0.31)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (1.2.7)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from fancyimpute) (3.6.4)
Collecting nose
  Downloading nose-1.3.7-py3-none-any.whl (154 kB)
     |████████████████████████████████| 154 kB 17.6 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.15.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.7/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (0.70.12.2)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (2.0.10)
Requirement already satisfied: scs>=1.1.3 in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (3.1.0)
Requirement already satisfied: osqp>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from cvxpy->fancyimpute) (0.6.2.post0)
Requirement already satisfied: qdldl in /usr/local/lib/python3.7/dist-packages (from osqp>=0.4.1->cvxpy->fancyimpute) (0.1.5.post0)
Requirement already satisfied: dill>=0.3.4 in /usr/local/lib/python3.7/dist-packages (from multiprocess->cvxpy->fancyimpute) (0.3.4)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (1.4.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (57.4.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (0.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (21.4.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->fancyimpute) (8.12.0)
Building wheels for collected packages: fancyimpute, knnimpute
  Building wheel for fancyimpute (setup.py) ... done
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29899 sha256=d0a656f8f5ba36ae84be7e966b448aa2ab82e145181ea4261c97989bf3a7dfd8
  Stored in directory: /root/.cache/pip/wheels/e3/04/06/a1a7d89ef4e631ce6268ea2d8cde04f7290651c1ff1025ce68
  Building wheel for knnimpute (setup.py) ... done
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11353 sha256=dc1dfd1a3061a84075b2cc0f06ce123bc6fad54220f2b459118476c8130cc985
  Stored in directory: /root/.cache/pip/wheels/72/21/a8/a045cacd9838abd5643f6bfa852c0796a99d6b1494760494e0
Successfully built fancyimpute knnimpute
Installing collected packages: nose, knnimpute, fancyimpute
Successfully installed fancyimpute-0.7.0 knnimpute-0.1.0 nose-1.3.7

In [12]:
from sklearn.ensemble import RandomForestRegressor
method=RandomForestRegressor()
MICE=IterativeImputer(estimator=method,max_iter=15)
Radiations=MICE.fit_transform(Radiations)

/usr/local/lib/python3.7/dist-packages/sklearn/impute/_iterative.py:701: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  ConvergenceWarning,

In [13]:
Radiations=pd.DataFrame(Radiations,columns=['YEAR','MN','DT','DTRAD','BHSS','W1','T'])

In [14]:
for i in range(len(tab2)):
  x=tab2.iloc[i,0]
  if(x!='-----'):
    y=float(x)
  else:
    y =float('nan')
  tab2.iloc[i,0]=y

tab2=tab2.groupby('INDEX').get_group(42101)

In [15]:
Table2=tab2[['INDEX','YEAR','MN','DT','..MAX','..MIN','AW','..R/F','DRNRF','RA','DZ','SN','SL','HA','TH','DS','FG','GA']]

In [16]:
Table2.head() #DRNRF    7536

         INDEX  YEAR MN DT ..MAX ..MIN    AW ..R/F  ... DZ SN SL HA TH DS FG GA
37643  42101.0  1970  1  1  21.6   9.1  13.0   0.0  ...  0  0  0  0  0  0  0  0
37644  42101.0  1970  1  2  22.7   8.5  20.0   0.0  ...  0  0  0  0  0  0  0  0
37645  42101.0  1970  1  3  23.1   6.7   4.0   0.0  ...  0  0  0  0  0  0  0  0
37646  42101.0  1970  1  4  22.4   6.3  10.0   0.0  ...  0  0  0  0  0  0  0  0
37647  42101.0  1970  1  5  22.9   2.7  10.0   0.0  ...  0  0  0  0  0  0  0  0

[5 rows x 18 columns]

In [17]:
Table2['RA'] = Table2['RA'].astype(float)
Table2['DZ'] = Table2['DZ'].astype(float)
Table2['SN'] = Table2['SN'].astype(float)
Table2['SL'] = Table2['SL'].astype(float)
Table2['HA'] = Table2['HA'].astype(float)
Table2['TH'] = Table2['TH'].astype(float)
Table2['DS'] = Table2['DS'].astype(float)
Table2['FG'] = Table2['FG'].astype(float)
Table2['GA'] = Table2['GA'].astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [18]:
for i in range(len(Table2)):
  x=Table2.iloc[i,1]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,1]=y
  x=Table2.iloc[i,2]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,2]=y
  x=Table2.iloc[i,3]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,3]=y
  x=Table2.iloc[i,4]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,4]=y
  x=Table2.iloc[i,5]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,5]=y
  x=Table2.iloc[i,5]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,5]=y
  x=Table2.iloc[i,6]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,6]=y

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [19]:
for i in range(len(Table2)):
  x=Table2.iloc[i,7]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table2.iloc[i,7]=y

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [20]:
#DRNRF    7536 hence to be dropped
Table2=Table2.drop(['DRNRF'],axis=1)

In [21]:
Table2.head()

         INDEX    YEAR   MN   DT ..MAX ..MIN  ...   SL   HA   TH   DS   FG   GA
37643  42101.0  1970.0  1.0  1.0  21.6   9.1  ...  0.0  0.0  0.0  0.0  0.0  0.0
37644  42101.0  1970.0  1.0  2.0  22.7   8.5  ...  0.0  0.0  0.0  0.0  0.0  0.0
37645  42101.0  1970.0  1.0  3.0  23.1   6.7  ...  0.0  0.0  0.0  0.0  0.0  0.0
37646  42101.0  1970.0  1.0  4.0  22.4   6.3  ...  0.0  0.0  0.0  0.0  0.0  0.0
37647  42101.0  1970.0  1.0  5.0  22.9   2.7  ...  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 17 columns]

In [22]:
Table2=MICE.fit_transform(Table2)

In [23]:
Table2=pd.DataFrame(Table2,columns=['INDEX','YEAR','MN','DT','..MAX','..MIN','AW','..R/F','RA','DZ','SN','SL','HA','TH','DS','FG','GA'])
Table2=Table2.drop(['INDEX'],axis=1)

In [24]:
Table2.isnull().sum()

YEAR     0
MN       0
DT       0
..MAX    0
..MIN    0
AW       0
..R/F    0
RA       0
DZ       0
SN       0
SL       0
HA       0
TH       0
DS       0
FG       0
GA       0
dtype: int64

In [25]:
for i in range(len(tab3)):
  x=tab3.iloc[i,0]
  if(x!='-----'):
    y=float(x)
  else:
    y =float('nan')
  tab3.iloc[i,0]=y

tab3=tab3.groupby('INDEX').get_group(42101)

In [26]:
Table3=tab3[['INDEX','YEAR','MN','DT','HR','AW','.RH']]

In [27]:
Table3.head()

         INDEX  YEAR MN DT HR    AW   .RH
73400  42101.0  1970  1  1  3  13.0  61.0
73401  42101.0  1970  1  2  3  21.0  60.0
73402  42101.0  1970  1  3  3   4.0  91.0
73403  42101.0  1970  1  4  3   9.0  72.0
73404  42101.0  1970  1  5  3   7.0  88.0

In [28]:
Table3.isnull().sum()

INDEX       0
YEAR        0
MN          0
DT          0
HR          0
AW       5826
.RH        13
dtype: int64

In [29]:
for i in range(len(Table3)):
  x=Table3.iloc[i,1]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,1]=y
  x=Table3.iloc[i,2]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,2]=y
  x=Table3.iloc[i,3]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,3]=y
  x=Table3.iloc[i,4]
  if(x!='-----'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,4]=y
  x=Table3.iloc[i,5]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,5]=y
  x=Table3.iloc[i,5]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,5]=y
  x=Table3.iloc[i,6]
  if(x!='-----' or x!='---'):
    y=float(x)
  else:
    y = float("nan")
  Table3.iloc[i,6]=y

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [30]:
Table3_HR3=Table3.groupby('HR').get_group(3)
Table3_HR12=Table3.groupby('HR').get_group(12)

In [31]:
Table3_HR3=MICE.fit_transform(Table3_HR3)
Table3_HR12=MICE.fit_transform(Table3_HR12)

In [32]:
Table3_HR3=pd.DataFrame(Table3_HR3,columns=['INDEX','YEAR','MN','DT','HR','AW','.RH'])
Table3_HR12=pd.DataFrame(Table3_HR12,columns=['INDEX','YEAR','MN','DT','HR','AW','.RH'])
Table3_HR3=Table3_HR3.drop(['INDEX'],axis=1)
Table3_HR12=Table3_HR12.drop(['INDEX'],axis=1)

In [33]:
mask=Table3_HR3['YEAR']>=1993.0 
Table3_HR3=Table3_HR3[mask]
mask2=Table3_HR3['YEAR']<=2010
Table3_HR3=Table3_HR3[mask2]
Table3_HR3

         YEAR    MN    DT   HR    AW    .RH
7564   1993.0   1.0   1.0  3.0  1.00   80.0
7565   1993.0   1.0   2.0  3.0  1.00   97.0
7566   1993.0   1.0   3.0  3.0  0.00  100.0
7567   1993.0   1.0   4.0  3.0  3.00  100.0
7568   1993.0   1.0   5.0  3.0  3.89   88.0
...       ...   ...   ...  ...   ...    ...
11543  2010.0  12.0  27.0  3.0  0.00  100.0
11544  2010.0  12.0  28.0  3.0  0.00  100.0
11545  2010.0  12.0  29.0  3.0  0.00   88.0
11546  2010.0  12.0  30.0  3.0  2.00  100.0
11547  2010.0  12.0  31.0  3.0  2.00   95.0

[3984 rows x 6 columns]

In [34]:
mask=Table3_HR12['YEAR']>=1993.0 
Table3_HR12=Table3_HR12[mask]
mask2=Table3_HR12['YEAR']<=2010
Table3_HR12=Table3_HR12[mask2]
Table3_HR12

         YEAR    MN    DT    HR   AW   .RH
7596   1993.0   1.0   1.0  12.0  5.0  75.0
7597   1993.0   1.0   2.0  12.0  3.0  72.0
7598   1993.0   1.0   3.0  12.0  4.0  80.0
7599   1993.0   1.0   4.0  12.0  9.0  65.0
7600   1993.0   1.0   5.0  12.0  9.0  74.0
...       ...   ...   ...   ...  ...   ...
11561  2010.0  12.0  27.0  12.0  0.0  88.0
11562  2010.0  12.0  28.0  12.0  1.0  78.0
11563  2010.0  12.0  29.0  12.0  1.0  85.0
11564  2010.0  12.0  30.0  12.0  2.0  85.0
11565  2010.0  12.0  31.0  12.0  2.0  89.0

[3970 rows x 6 columns]

In [35]:
Table3_HR12

         YEAR    MN    DT    HR   AW   .RH
7596   1993.0   1.0   1.0  12.0  5.0  75.0
7597   1993.0   1.0   2.0  12.0  3.0  72.0
7598   1993.0   1.0   3.0  12.0  4.0  80.0
7599   1993.0   1.0   4.0  12.0  9.0  65.0
7600   1993.0   1.0   5.0  12.0  9.0  74.0
...       ...   ...   ...   ...  ...   ...
11561  2010.0  12.0  27.0  12.0  0.0  88.0
11562  2010.0  12.0  28.0  12.0  1.0  78.0
11563  2010.0  12.0  29.0  12.0  1.0  85.0
11564  2010.0  12.0  30.0  12.0  2.0  85.0
11565  2010.0  12.0  31.0  12.0  2.0  89.0

[3970 rows x 6 columns]

In [36]:
mask=Radiations['YEAR']>=1993.0 
Radiations=Radiations[mask]
mask2=Radiations['YEAR']<=2010
Radiations=Radiations[mask2]
Radiations

        YEAR    MN    DT    DTRAD   BHSS     W1      T
519   1993.0   1.0   1.0   6.0500  1.600  14.00   7.00
520   1993.0   1.0   2.0   8.9600  6.600  14.00  14.00
521   1993.0   1.0   3.0   7.3400  2.500  12.00   7.00
522   1993.0   1.0   4.0  11.5600  7.800  12.00  14.00
523   1993.0   1.0   5.0   6.8300  1.000   2.00  14.00
...      ...   ...   ...      ...    ...    ...    ...
5781  2010.0  12.0  27.0   9.0500  1.600   3.00  14.00
5782  2010.0  12.0  28.0   7.7200  0.000   3.00  14.00
5783  2010.0  12.0  29.0   4.2400  0.000   3.00  14.00
5784  2010.0  12.0  30.0   3.8500  0.300   3.00  14.00
5785  2010.0  12.0  31.0   9.9535  3.063  12.03   5.95

[5267 rows x 7 columns]

In [37]:
from scipy import stats
import scipy

In [38]:
Table3_HR3=Table3_HR3.drop(['HR','AW'],axis=1)
Table3_HR12=Table3_HR12.drop(['HR','AW'],axis=1)

In [39]:
humid=pd.DataFrame()
humid=Table3_HR3.merge(Table3_HR12,on=['YEAR','MN','DT'],how='right')

In [40]:
humid

        YEAR    MN    DT  .RH_x  .RH_y
0     1993.0   1.0   1.0   80.0   75.0
1     1993.0   1.0   2.0   97.0   72.0
2     1993.0   1.0   3.0  100.0   80.0
3     1993.0   1.0   4.0  100.0   65.0
4     1993.0   1.0   5.0   88.0   74.0
...      ...   ...   ...    ...    ...
3965  2010.0  12.0  27.0  100.0   88.0
3966  2010.0  12.0  28.0  100.0   78.0
3967  2010.0  12.0  29.0   88.0   85.0
3968  2010.0  12.0  30.0  100.0   85.0
3969  2010.0  12.0  31.0   95.0   89.0

[3970 rows x 5 columns]

In [41]:
for i in range(len(humid)):
  if(humid.iloc[i][3]>humid.iloc[i][4]):
    humid.iloc[i][3],humid.iloc[i][4]=humid.iloc[i][4],humid.iloc[i][3]

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

In [42]:
humid['avg_RH']=humid[['.RH_x','.RH_y']].mean(axis=1) #.RH_x min humidity

In [43]:
mask=Table2['YEAR']>=1993.0 
Table2=Table2[mask]
mask2=Table2['YEAR']<=2010
Table2=Table2[mask2]
Table2

         YEAR    MN    DT  ..MAX  ..MIN   AW  ...   SL   HA   TH   DS   FG   GA
7653   1993.0   1.0   1.0   20.5   13.5  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7654   1993.0   1.0   2.0   21.3   10.3  2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7655   1993.0   1.0   3.0   23.5   11.4  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7656   1993.0   1.0   4.0   20.7    8.4  3.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7657   1993.0   1.0   5.0   20.7    8.5  7.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
...       ...   ...   ...    ...    ...  ...  ...  ...  ...  ...  ...  ...  ...
11286  2010.0  12.0  27.0   15.8    4.5  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
11287  2010.0  12.0  28.0   16.8    4.5  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0
11288  2010.0  12.0  29.0   16.8    3.4  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
11289  2010.0  12.0  30.0   18.1    8.7  1.0  ...  0.0  0.0  1.0  0.0  0.0  0.0
11290  2010.0  12.0  31.0   17.1   11.0  2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

[3638 rows x 16 columns]

In [44]:
#Table3=Table3.drop(['AW'],axis=1)
# Table2=Table2.drop(['AW'],axis=1)
Table2.head()

        YEAR   MN   DT  ..MAX  ..MIN   AW  ...   SL   HA   TH   DS   FG   GA
7653  1993.0  1.0  1.0   20.5   13.5  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7654  1993.0  1.0  2.0   21.3   10.3  2.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7655  1993.0  1.0  3.0   23.5   11.4  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7656  1993.0  1.0  4.0   20.7    8.4  3.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
7657  1993.0  1.0  5.0   20.7    8.5  7.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 16 columns]

In [45]:
Table3.shape

(26143, 7)

In [46]:
Final_data=Table2.merge(humid,on=['YEAR','MN','DT'],how='left').merge(Radiations,on=['YEAR','MN','DT'],how='left')
Final_data=Final_data.drop(['RA','DZ','SN','SL','HA','TH','DS','FG','GA','W1','T','avg_RH'],axis=1)

In [47]:
Final_data.head()

     YEAR   MN   DT  ..MAX  ..MIN   AW  ..R/F  .RH_x  .RH_y  DTRAD  BHSS
0  1993.0  1.0  1.0   20.5   13.5  1.0    0.0   80.0   75.0   6.05   1.6
1  1993.0  1.0  2.0   21.3   10.3  2.0    0.0   97.0   72.0   8.96   6.6
2  1993.0  1.0  3.0   23.5   11.4  1.0    0.0  100.0   80.0   7.34   2.5
3  1993.0  1.0  4.0   20.7    8.4  3.0    0.0  100.0   65.0  11.56   7.8
4  1993.0  1.0  5.0   20.7    8.5  7.0    0.0   88.0   74.0   6.83   1.0

In [48]:
Final=MICE.fit_transform(Final_data)

/usr/local/lib/python3.7/dist-packages/sklearn/impute/_iterative.py:701: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  ConvergenceWarning,

In [49]:
Final_data=pd.DataFrame(Final,columns=['Year','MN','DT','T_max','T_min','U_z','Rainfall','RH_min','RH_max','R_n','n_sun'])
Final_data=Final_data.drop(['Rainfall'],axis=1)
Final_data.isnull().sum()

Year      0
MN        0
DT        0
T_max     0
T_min     0
U_z       0
RH_min    0
RH_max    0
R_n       0
n_sun     0
dtype: int64

In [50]:
Final_data['Year']=Final_data['Year'].astype(int)
Final_data['MN']=Final_data['MN'].astype(int)
Final_data['DT']=Final_data['DT'].astype(int)
Final_data['Year']=Final_data['Year'].astype(str)
Final_data['MN']=Final_data['MN'].astype(str)
Final_data['DT']=Final_data['DT'].astype(str)
col=['-'.join(i) for i in zip((Final_data['Year']),(Final_data['MN']),(Final_data['DT']))]
print(col)
Final_data.insert(0,'date',col)
Final_data=Final_data.drop(['Year','MN','DT'],axis=1)
Final_data['date']=pd.to_datetime(Final_data['date']).dt.strftime('%Y-%m-%d')
Final_data.isnull().sum()

['1993-1-1', '1993-1-2', '1993-1-3', '1993-1-4', '1993-1-5', '1993-1-6', '1993-1-7', '1993-1-8', '1993-1-9', '1993-1-10', '1993-1-11', '1993-1-12', '1993-1-13', '1993-1-14', '1993-1-15', '1993-1-16', '1993-1-17', '1993-1-18', '1993-1-19', '1993-1-20', '1993-1-21', '1993-1-22', '1993-1-23', '1993-1-24', '1993-1-25', '1993-1-26', '1993-1-27', '1993-1-28', '1993-1-29', '1993-1-30', '1993-1-31', '1993-2-1', '1993-2-2', '1993-2-3', '1993-2-4', '1993-2-5', '1993-2-6', '1993-2-7', '1993-2-8', '1993-2-9', '1993-2-10', '1993-2-11', '1993-2-12', '1993-2-13', '1993-2-14', '1993-2-15', '1993-2-16', '1993-2-17', '1993-2-18', '1993-2-19', '1993-2-20', '1993-2-21', '1993-2-22', '1993-2-23', '1993-2-24', '1993-2-25', '1993-2-26', '1993-2-27', '1993-2-28', '1993-3-1', '1993-3-2', '1993-3-3', '1993-3-4', '1993-3-5', '1993-3-6', '1993-3-7', '1993-3-8', '1993-3-9', '1993-3-10', '1993-3-11', '1993-3-12', '1993-3-13', '1993-3-14', '1993-3-15', '1993-3-16', '1993-3-17', '1993-3-18', '1993-3-19', '1993-3-20', '1993-3-21', '1993-3-22', '1993-3-23', '1993-3-24', '1993-3-25', '1993-3-26', '1993-3-27', '1993-3-28', '1993-3-29', '1993-3-30', '1993-3-31', '1993-4-1', '1993-4-2', '1993-4-3', '1993-4-4', '1993-4-5', '1993-4-6', '1993-4-7', '1993-4-8', '1993-4-9', '1993-4-10', '1993-4-11', '1993-4-12', '1993-4-13', '1993-4-14', '1993-4-15', '1993-4-16', '1993-4-17', '1993-4-18', '1993-4-19', '1993-4-20', '1993-4-21', '1993-4-22', '1993-4-23', '1993-4-24', '1993-4-25', '1993-4-26', '1993-4-27', '1993-4-28', '1993-4-29', '1993-4-30', '1993-5-1', '1993-5-2', '1993-5-3', '1993-5-4', '1993-5-5', '1993-5-6', '1993-5-7', '1993-5-8', '1993-5-9', '1993-5-10', '1993-5-11', '1993-5-12', '1993-5-13', '1993-5-14', '1993-5-15', '1993-5-16', '1993-5-17', '1993-5-18', '1993-5-19', '1993-5-20', '1993-5-21', '1993-5-22', '1993-5-23', '1993-5-24', '1993-5-25', '1993-5-26', '1993-5-27', '1993-5-28', '1993-5-29', '1993-5-30', '1993-5-31', '1993-6-1', '1993-6-2', '1993-6-3', '1993-6-4', '1993-6-5', '1993-6-6', '1993-6-7', '1993-6-8', '1993-6-9', '1993-6-10', '1993-6-11', '1993-6-12', '1993-6-13', '1993-6-14', '1993-6-15', '1993-6-16', '1993-6-17', '1993-6-18', '1993-6-19', '1993-6-20', '1993-6-21', '1993-6-22', '1993-6-23', '1993-6-24', '1993-6-25', '1993-6-26', '1993-6-27', '1993-6-28', '1993-6-29', '1993-6-30', '1993-7-1', '1993-7-2', '1993-7-3', '1993-7-4', '1993-7-5', '1993-7-6', '1993-7-7', '1993-7-8', '1993-7-9', '1993-7-10', '1993-7-11', '1993-7-12', '1993-7-13', '1993-7-14', '1993-7-15', '1993-7-16', '1993-7-17', '1993-7-18', '1993-7-19', '1993-7-20', '1993-7-21', '1993-7-22', '1993-7-23', '1993-7-24', '1993-7-25', '1993-7-26', '1993-7-27', '1993-7-28', '1993-7-29', '1993-7-30', '1993-7-31', '1993-8-1', '1993-8-2', '1993-8-3', '1993-8-4', '1993-8-5', '1993-8-6', '1993-8-7', '1993-8-8', '1993-8-9', '1993-8-10', '1993-8-11', '1993-8-12', '1993-8-13', '1993-8-14', '1993-8-15', '1993-8-16', '1993-8-17', '1993-8-18', '1993-8-19', '1993-8-20', '1993-8-21', '1993-8-22', '1993-8-23', '1993-8-24', '1993-8-25', '1993-8-26', '1993-8-27', '1993-8-28', '1993-8-29', '1993-8-30', '1993-8-31', '1993-9-1', '1993-9-2', '1993-9-3', '1993-9-4', '1993-9-5', '1993-9-6', '1993-9-7', '1993-9-8', '1993-9-9', '1993-9-10', '1993-9-11', '1993-9-12', '1993-9-13', '1993-9-14', '1993-9-15', '1993-9-16', '1993-9-17', '1993-9-18', '1993-9-19', '1993-9-20', '1993-9-21', '1993-9-22', '1993-9-23', '1993-9-24', '1993-9-25', '1993-9-26', '1993-9-27', '1993-9-28', '1993-9-29', '1993-9-30', '1993-10-1', '1993-10-2', '1993-10-3', '1993-10-4', '1993-10-5', '1993-10-6', '1993-10-7', '1993-10-8', '1993-10-9', '1993-10-10', '1993-10-11', '1993-10-12', '1993-10-13', '1993-10-14', '1993-10-15', '1993-10-16', '1993-10-17', '1993-10-18', '1993-10-19', '1993-10-20', '1993-10-21', '1993-10-22', '1993-10-23', '1993-10-24', '1993-10-25', '1993-10-26', '1993-10-27', '1993-10-28', '1993-10-29', '1993-10-30', '1993-10-31', '1993-11-1', '1993-11-2', '1993-11-3', '1993-11-4', '1993-11-5', '1993-11-6', '1993-11-7', '1993-11-8', '1993-11-9', '1993-11-10', '1993-11-11', '1993-11-12', '1993-11-13', '1993-11-14', '1993-11-15', '1993-11-16', '1993-11-17', '1993-11-18', '1993-11-19', '1993-11-20', '1993-11-21', '1993-11-22', '1993-11-23', '1993-11-24', '1993-11-25', '1993-11-26', '1993-11-27', '1993-11-28', '1993-11-29', '1993-11-30', '1993-12-1', '1993-12-2', '1993-12-3', '1993-12-4', '1993-12-5', '1993-12-6', '1993-12-7', '1993-12-8', '1993-12-9', '1993-12-10', '1993-12-11', '1993-12-12', '1993-12-13', '1993-12-14', '1993-12-15', '1993-12-16', '1993-12-17', '1993-12-18', '1993-12-19', '1993-12-20', '1993-12-21', '1993-12-22', '1993-12-23', '1993-12-24', '1993-12-25', '1993-12-26', '1993-12-27', '1993-12-28', '1993-12-29', '1993-12-30', '1993-12-31', '1994-1-1', '1994-1-2', '1994-1-3', '1994-1-4', '1994-1-5', '1994-1-6', '1994-1-7', '1994-1-8', '1994-1-9', '1994-1-10', '1994-1-11', '1994-1-12', '1994-1-13', '1994-1-14', '1994-1-15', '1994-1-16', '1994-1-17', '1994-1-18', '1994-1-19', '1994-1-20', '1994-1-21', '1994-1-22', '1994-1-23', '1994-1-24', '1994-1-25', '1994-1-26', '1994-1-27', '1994-1-28', '1994-1-29', '1994-1-30', '1994-1-31', '1994-2-1', '1994-2-2', '1994-2-3', '1994-2-4', '1994-2-5', '1994-2-6', '1994-2-7', '1994-2-8', '1994-2-9', '1994-2-10', '1994-2-11', '1994-2-12', '1994-2-13', '1994-2-14', '1994-2-15', '1994-2-16', '1994-2-17', '1994-2-18', '1994-2-19', '1994-2-20', '1994-2-21', '1994-2-22', '1994-2-23', '1994-2-24', '1994-2-25', '1994-2-26', '1994-2-27', '1994-2-28', '1994-3-1', '1994-3-2', '1994-3-3', '1994-3-4', '1994-3-5', '1994-3-6', '1994-3-7', '1994-3-8', '1994-3-9', '1994-3-10', '1994-3-11', '1994-3-12', '1994-3-13', '1994-3-14', '1994-3-15', '1994-3-16', '1994-3-17', '1994-3-18', '1994-3-19', '1994-3-20', '1994-3-21', '1994-3-22', '1994-3-23', '1994-3-24', '1994-3-25', '1994-3-26', '1994-3-27', '1994-3-28', '1994-3-29', '1994-3-30', '1994-3-31', '1994-4-1', '1994-4-2', '1994-4-3', '1994-4-4', '1994-4-5', '1994-4-6', '1994-4-7', '1994-4-8', '1994-4-9', '1994-4-10', '1994-4-11', '1994-4-12', '1994-4-13', '1994-4-14', '1994-4-15', '1994-4-16', '1994-4-17', '1994-4-18', '1994-4-19', '1994-4-20', '1994-4-21', '1994-4-22', '1994-4-23', '1994-4-24', '1994-4-25', '1994-4-26', '1994-4-27', '1994-4-28', '1994-4-29', '1994-4-30', '1994-5-1', '1994-5-2', '1994-5-3', '1994-5-4', '1994-5-5', '1994-5-6', '1994-5-7', '1994-5-8', '1994-5-9', '1994-5-10', '1994-5-11', '1994-5-12', '1994-5-13', '1994-5-14', '1994-5-15', '1994-5-16', '1994-5-17', '1994-5-18', '1994-5-19', '1994-5-20', '1994-5-21', '1994-5-22', '1994-5-23', '1994-5-24', '1994-5-25', '1994-5-26', '1994-5-27', '1994-5-28', '1994-5-29', '1994-5-30', '1994-5-31', '1994-6-1', '1994-6-2', '1994-6-3', '1994-6-4', '1994-6-5', '1994-6-6', '1994-6-7', '1994-6-8', '1994-6-9', '1994-6-10', '1994-6-11', '1994-6-12', '1994-6-13', '1994-6-14', '1994-6-15', '1994-6-16', '1994-6-17', '1994-6-18', '1994-6-19', '1994-6-20', '1994-6-21', '1994-6-22', '1994-6-23', '1994-6-24', '1994-6-25', '1994-6-26', '1994-6-27', '1994-6-28', '1994-6-29', '1994-6-30', '1994-7-1', '1994-7-2', '1994-7-3', '1994-7-4', '1994-7-5', '1994-7-6', '1994-7-7', '1994-7-8', '1994-7-9', '1994-7-10', '1994-7-11', '1994-7-12', '1994-7-13', '1994-7-14', '1994-7-15', '1994-7-16', '1994-7-17', '1994-7-18', '1994-7-19', '1994-7-20', '1994-7-21', '1994-7-22', '1994-7-23', '1994-7-24', '1994-7-25', '1994-7-26', '1994-7-27', '1994-7-28', '1994-7-29', '1994-7-30', '1994-7-31', '1994-8-1', '1994-8-2', '1994-8-3', '1994-8-4', '1994-8-5', '1994-8-6', '1994-8-7', '1994-8-8', '1994-8-9', '1994-8-10', '1994-8-11', '1994-8-12', '1994-8-13', '1994-8-14', '1994-8-15', '1994-8-16', '1994-8-17', '1994-8-18', '1994-8-19', '1994-8-20', '1994-8-21', '1994-8-22', '1994-8-23', '1994-8-24', '1994-8-25', '1994-8-26', '1994-8-27', '1994-8-28', '1994-8-29', '1994-8-30', '1994-8-31', '1994-9-1', '1994-9-2', '1994-9-3', '1994-9-4', '1994-9-5', '1994-9-6', '1994-9-7', '1994-9-8', '1994-9-9', '1994-9-10', '1994-9-11', '1994-9-12', '1994-9-13', '1994-9-14', '1994-9-15', '1994-9-16', '1994-9-17', '1994-9-18', '1994-9-19', '1994-9-20', '1994-9-21', '1994-9-22', '1994-9-23', '1994-9-24', '1994-9-25', '1994-9-26', '1994-9-27', '1994-9-28', '1994-9-29', '1994-9-30', '1994-10-1', '1994-10-2', '1994-10-3', '1994-10-4', '1994-10-5', '1994-10-6', '1994-10-7', '1994-10-8', '1994-10-9', '1994-10-10', '1994-10-11', '1994-10-12', '1994-10-13', '1994-10-14', '1994-10-15', '1994-10-16', '1994-10-17', '1994-10-18', '1994-10-19', '1994-10-20', '1994-10-21', '1994-10-22', '1994-10-23', '1994-10-24', '1994-10-25', '1994-10-26', '1994-10-27', '1994-10-28', '1994-10-29', '1994-10-30', '1994-10-31', '1994-11-1', '1994-11-2', '1994-11-3', '1994-11-4', '1994-11-5', '1994-11-6', '1994-11-7', '1994-11-8', '1994-11-9', '1994-11-10', '1994-11-11', '1994-11-12', '1994-11-13', '1994-11-14', '1994-11-15', '1994-11-16', '1994-11-17', '1994-11-18', '1994-11-19', '1994-11-20', '1994-11-21', '1994-11-22', '1994-11-23', '1994-11-24', '1994-11-25', '1994-11-26', '1994-11-27', '1994-11-28', '1994-11-29', '1994-11-30', '1994-12-1', '1994-12-2', '1994-12-3', '1994-12-4', '1994-12-5', '1994-12-6', '1994-12-7', '1994-12-8', '1994-12-9', '1994-12-10', '1994-12-11', '1994-12-12', '1994-12-13', '1994-12-14', '1994-12-15', '1994-12-16', '1994-12-17', '1994-12-18', '1994-12-19', '1994-12-20', '1994-12-21', '1994-12-22', '1994-12-23', '1994-12-24', '1994-12-25', '1994-12-26', '1994-12-27', '1994-12-28', '1994-12-29', '1994-12-30', '1994-12-31', '1995-1-1', '1995-1-2', '1995-1-3', '1995-1-4', '1995-1-5', '1995-1-6', '1995-1-7', '1995-1-8', '1995-1-9', '1995-1-10', '1995-1-11', '1995-1-12', '1995-1-13', '1995-1-14', '1995-1-15', '1995-1-16', '1995-1-17', '1995-1-18', '1995-1-19', '1995-1-20', '1995-1-21', '1995-1-22', '1995-1-23', '1995-1-24', '1995-1-25', '1995-1-26', '1995-1-27', '1995-1-28', '1995-1-29', '1995-1-30', '1995-1-31', '1995-2-1', '1995-2-2', '1995-2-3', '1995-2-4', '1995-2-5', '1995-2-6', '1995-2-7', '1995-2-8', '1995-2-9', '1995-2-10', '1995-2-11', '1995-2-12', '1995-2-13', '1995-2-14', '1995-2-15', '1995-2-16', '1995-2-17', '1995-2-18', '1995-2-19', '1995-2-20', '1995-2-21', '1995-2-22', '1995-2-23', '1995-2-24', '1995-2-25', '1995-2-26', '1995-2-27', '1995-2-28', '1995-3-1', '1995-3-2', '1995-3-3', '1995-3-4', '1995-3-5', '1995-3-6', '1995-3-7', '1995-3-8', '1995-3-9', '1995-3-10', '1995-3-11', '1995-3-12', '1995-3-13', '1995-3-14', '1995-3-15', '1995-3-16', '1995-3-17', '1995-3-18', '1995-3-19', '1995-3-20', '1995-3-21', '1995-3-22', '1995-3-23', '1995-3-24', '1995-3-25', '1995-3-26', '1995-3-27', '1995-3-28', '1995-3-29', '1995-3-30', '1995-3-31', '1995-4-1', '1995-4-2', '1995-4-3', '1995-4-4', '1995-4-5', '1995-4-6', '1995-4-7', '1995-4-8', '1995-4-9', '1995-4-10', '1995-4-11', '1995-4-12', '1995-4-13', '1995-4-14', '1995-4-15', '1995-4-16', '1995-4-17', '1995-4-18', '1995-4-19', '1995-4-20', '1995-4-21', '1995-4-22', '1995-4-23', '1995-4-24', '1995-4-25', '1995-4-26', '1995-4-27', '1995-4-28', '1995-4-29', '1995-4-30', '1995-5-1', '1995-5-2', '1995-5-3', '1995-5-4', '1995-5-5', '1995-5-6', '1995-5-7', '1995-5-8', '1995-5-9', '1995-5-10', '1995-5-11', '1995-5-12', '1995-5-13', '1995-5-14', '1995-5-15', '1995-5-16', '1995-5-17', '1995-5-18', '1995-5-19', '1995-5-20', '1995-5-21', '1995-5-22', '1995-5-23', '1995-5-24', '1995-5-25', '1995-5-26', '1995-5-27', '1995-5-28', '1995-5-29', '1995-5-30', '1995-5-31', '1995-6-1', '1995-6-2', '1995-6-3', '1995-6-4', '1995-6-5', '1995-6-6', '1995-6-7', '1995-6-8', '1995-6-9', '1995-6-10', '1995-6-11', '1995-6-12', '1995-6-13', '1995-6-14', '1995-6-15', '1995-6-16', '1995-6-17', '1995-6-18', '1995-6-19', '1995-6-20', '1995-6-21', '1995-6-22', '1995-6-23', '1995-6-24', '1995-6-25', '1995-6-26', '1995-6-27', '1995-6-28', '1995-6-29', '1995-6-30', '1995-7-1', '1995-7-2', '1995-7-3', '1995-7-4', '1995-7-5', '1995-7-6', '1995-7-7', '1995-7-8', '1995-7-9', '1995-7-10', '1995-7-11', '1995-7-12', '1995-7-13', '1995-7-14', '1995-7-15', '1995-7-16', '1995-7-17', '1995-7-18', '1995-7-19', '1995-7-20', '1995-7-21', '1995-7-22', '1995-7-23', '1995-7-24', '1995-7-25', '1995-7-26', '1995-7-27', '1995-7-28', '1995-7-29', '1995-7-30', '1995-7-31', '1995-8-1', '1995-8-2', '1995-8-3', '1995-8-4', '1995-8-5', '1995-8-6', '1995-8-7', '1995-8-8', '1995-8-9', '1995-8-10', '1995-8-11', '1995-8-12', '1995-8-13', '1995-8-14', '1995-8-15', '1995-8-16', '1995-8-17', '1995-8-18', '1995-8-19', '1995-8-20', '1995-8-21', '1995-8-22', '1995-8-23', '1995-8-24', '1995-8-25', '1995-8-26', '1995-8-27', '1995-8-28', '1995-8-29', '1995-8-30', '1995-8-31', '1995-9-1', '1995-9-2', '1995-9-3', '1995-9-4', '1995-9-5', '1995-9-6', '1995-9-7', '1995-9-8', '1995-9-9', '1995-9-10', '1995-9-11', '1995-9-12', '1995-9-13', '1995-9-14', '1995-9-15', '1995-9-16', '1995-9-17', '1995-9-18', '1995-9-19', '1995-9-20', '1995-9-21', '1995-9-22', '1995-9-23', '1995-9-24', '1995-9-25', '1995-9-26', '1995-9-27', '1995-9-28', '1995-9-29', '1995-9-30', '1995-10-1', '1995-10-2', '1995-10-3', '1995-10-4', '1995-10-5', '1995-10-6', '1995-10-7', '1995-10-8', '1995-10-9', '1995-10-10', '1995-10-11', '1995-10-12', '1995-10-13', '1995-10-14', '1995-10-15', '1995-10-16', '1995-10-17', '1995-10-18', '1995-10-19', '1995-10-20', '1995-10-21', '1995-10-22', '1995-10-23', '1995-10-24', '1995-10-25', '1995-10-26', '1995-10-27', '1995-10-28', '1995-10-29', '1995-10-30', '1995-10-31', '1995-11-1', '1995-11-2', '1995-11-3', '1995-11-4', '1995-11-5', '1995-11-6', '1995-11-7', '1995-11-8', '1995-11-9', '1995-11-10', '1995-11-11', '1995-11-12', '1995-11-13', '1995-11-14', '1995-11-15', '1995-11-16', '1995-11-17', '1995-11-18', '1995-11-19', '1995-11-20', '1995-11-21', '1995-11-22', '1995-11-23', '1995-11-24', '1995-11-25', '1995-11-26', '1995-11-27', '1995-11-28', '1995-11-29', '1995-11-30', '1995-12-1', '1995-12-2', '1995-12-3', '1995-12-4', '1995-12-5', '1995-12-6', '1995-12-7', '1995-12-8', '1995-12-9', '1995-12-10', '1995-12-11', '1995-12-12', '1995-12-13', '1995-12-14', '1995-12-15', '1995-12-16', '1995-12-17', '1995-12-18', '1995-12-19', '1995-12-20', '1995-12-21', '1995-12-22', '1995-12-23', '1995-12-24', '1995-12-25', '1995-12-26', '1995-12-27', '1995-12-28', '1995-12-29', '1995-12-30', '1995-12-31', '1996-1-1', '1996-1-2', '1996-1-3', '1996-1-4', '1996-1-5', '1996-1-6', '1996-1-7', '1996-1-8', '1996-1-9', '1996-1-10', '1996-1-11', '1996-1-12', '1996-1-13', '1996-1-14', '1996-1-15', '1996-1-16', '1996-1-17', '1996-1-18', '1996-1-19', '1996-1-20', '1996-1-21', '1996-1-22', '1996-1-23', '1996-1-24', '1996-1-25', '1996-1-26', '1996-1-27', '1996-1-29', '1996-1-30', '1996-1-31', '1996-2-1', '1996-2-2', '1996-2-3', '1996-2-4', '1996-2-6', '1996-2-7', '1996-2-8', '1996-2-9', '1996-2-10', '1996-2-11', '1996-2-12', '1996-2-13', '1996-2-14', '1996-2-15', '1996-2-16', '1996-2-17', '1996-2-18', '1996-2-19', '1996-2-20', '1996-2-21', '1996-2-22', '1996-2-23', '1996-2-24', '1996-2-25', '1996-2-26', '1996-2-27', '1996-2-28', '1996-2-29', '1996-3-1', '1996-3-2', '1996-3-3', '1996-3-4', '1996-3-5', '1996-3-6', '1996-3-7', '1996-3-8', '1996-3-9', '1996-3-10', '1996-3-11', '1996-3-12', '1996-3-13', '1996-3-14', '1996-3-15', '1996-3-16', '1996-3-17', '1996-3-18', '1996-3-19', '1996-3-20', '1996-3-21', '1996-3-22', '1996-3-23', '1996-3-24', '1996-3-25', '1996-3-26', '1996-3-27', '1996-3-28', '1996-3-29', '1996-3-30', '1996-3-31', '1996-4-1', '1996-4-2', '1996-4-3', '1996-4-4', '1996-4-5', '1996-4-6', '1996-4-7', '1996-4-8', '1996-4-9', '1996-4-10', '1996-4-11', '1996-4-12', '1996-4-13', '1996-4-14', '1996-4-15', '1996-4-16', '1996-4-17', '1996-4-18', '1996-4-19', '1996-4-20', '1996-4-21', '1996-4-22', '1996-4-23', '1996-4-24', '1996-4-25', '1996-4-26', '1996-4-27', '1996-4-28', '1996-4-29', '1996-4-30', '1996-5-1', '1996-5-2', '1996-5-3', '1996-5-4', '1996-5-5', '1996-5-6', '1996-5-7', '1996-5-8', '1996-5-9', '1996-5-10', '1996-5-11', '1996-5-12', '1996-5-13', '1996-5-14', '1996-5-15', '1996-5-17', '1996-5-18', '1996-5-19', '1996-5-20', '1996-5-21', '1996-5-22', '1996-5-23', '1996-5-24', '1996-5-25', '1996-5-26', '1996-5-27', '1996-5-28', '1996-5-29', '1996-5-30', '1996-5-31', '1996-6-1', '1996-6-2', '1996-6-3', '1996-6-4', '1996-6-5', '1996-6-6', '1996-6-7', '1996-6-9', '1996-6-10', '1996-6-11', '1996-6-12', '1996-6-13', '1996-6-14', '1996-6-15', '1996-6-16', '1996-6-17', '1996-6-18', '1996-6-19', '1996-6-20', '1996-6-21', '1996-6-22', '1996-6-23', '1996-6-24', '1996-6-25', '1996-6-26', '1996-6-27', '1996-6-28', '1996-6-29', '1996-6-30', '1996-7-1', '1996-7-2', '1996-7-3', '1996-7-4', '1996-7-5', '1996-7-6', '1996-7-7', '1996-7-8', '1996-7-9', '1996-7-10', '1996-7-11', '1996-7-12', '1996-7-13', '1996-7-14', '1996-7-15', '1996-7-16', '1996-7-17', '1996-7-18', '1996-7-19', '1996-7-20', '1996-7-21', '1996-7-22', '1996-7-23', '1996-7-24', '1996-7-25', '1996-7-26', '1996-7-27', '1996-7-28', '1996-7-29', '1996-7-30', '1996-7-31', '1996-8-1', '1996-8-2', '1996-8-3', '1996-8-4', '1996-8-5', '1996-8-6', '1996-8-7', '1996-8-8', '1996-8-9', '1996-8-10', '1996-8-11', '1996-8-12', '1996-8-13', '1996-8-14', '1996-8-15', '1996-8-16', '1996-8-17', '1996-8-18', '1996-8-19', '1996-8-20', '1996-8-21', '1996-8-23', '1996-8-24', '1996-8-25', '1996-8-26', '1996-8-27', '1996-8-28', '1996-8-29', '1996-8-30', '1996-8-31', '1996-9-1', '1996-9-2', '1996-9-3', '1996-9-4', '1996-9-5', '1996-9-6', '1996-9-7', '1996-9-8', '1996-9-9', '1996-9-10', '1996-9-11', '1996-9-12', '1996-9-13', '1996-9-14', '1996-9-15', '1996-9-16', '1996-9-17', '1996-9-18', '1996-9-19', '1996-9-20', '1996-9-21', '1996-9-22', '1996-9-23', '1996-9-24', '1996-9-25', '1996-9-26', '1996-9-27', '1996-9-28', '1996-9-29', '1996-9-30', '1996-10-1', '1996-10-2', '1996-10-3', '1996-10-4', '1996-10-5', '1996-10-6', '1996-10-7', '1996-10-8', '1996-10-9', '1996-10-10', '1996-10-11', '1996-10-12', '1996-10-13', '1996-10-14', '1996-10-15', '1996-10-16', '1996-10-17', '1996-10-18', '1996-10-19', '1996-10-20', '1996-10-21', '1996-10-22', '1996-10-23', '1996-10-24', '1996-10-25', '1996-10-26', '1996-10-27', '1996-10-28', '1996-10-29', '1996-10-30', '1996-10-31', '1996-11-1', '1996-11-2', '1996-11-3', '1996-11-4', '1996-11-5', '1996-11-6', '1996-11-7', '1996-11-8', '1996-11-9', '1996-11-10', '1996-11-11', '1996-11-12', '1996-11-13', '1996-11-14', '1996-11-15', '1996-11-16', '1996-11-17', '1996-11-18', '1996-11-19', '1996-11-20', '1996-11-21', '1996-11-22', '1996-11-23', '1996-11-24', '1996-11-25', '1996-11-26', '1996-11-27', '1996-11-28', '1996-11-29', '1996-11-30', '1996-12-1', '1996-12-2', '1996-12-3', '1996-12-4', '1996-12-5', '1996-12-6', '1996-12-7', '1996-12-8', '1996-12-9', '1996-12-10', '1996-12-11', '1996-12-12', '1996-12-13', '1996-12-14', '1996-12-15', '1996-12-16', '1996-12-17', '1996-12-18', '1996-12-19', '1996-12-20', '1996-12-21', '1996-12-22', '1996-12-23', '1996-12-24', '1996-12-25', '1996-12-26', '1996-12-27', '1996-12-28', '1996-12-29', '1996-12-30', '1996-12-31', '1997-1-1', '1997-1-2', '1997-1-3', '1997-1-4', '1997-1-5', '1997-1-6', '1997-1-7', '1997-1-8', '1997-1-9', '1997-1-10', '1997-1-11', '1997-1-12', '1997-1-13', '1997-1-14', '1997-1-15', '1997-1-16', '1997-1-17', '1997-1-18', '1997-1-19', '1997-1-20', '1997-1-21', '1997-1-22', '1997-1-23', '1997-1-24', '1997-1-25', '1997-1-26', '1997-1-27', '1997-1-28', '1997-1-29', '1997-1-30', '1997-1-31', '1997-2-1', '1997-2-2', '1997-2-3', '1997-2-4', '1997-2-5', '1997-2-6', '1997-2-7', '1997-2-8', '1997-2-9', '1997-2-10', '1997-2-11', '1997-2-12', '1997-2-13', '1997-2-14', '1997-2-15', '1997-2-16', '1997-2-17', '1997-2-18', '1997-2-19', '1997-2-20', '1997-2-21', '1997-2-22', '1997-2-23', '1997-2-24', '1997-2-25', '1997-2-26', '1997-2-27', '1997-2-28', '1997-3-1', '1997-3-2', '1997-3-3', '1997-3-4', '1997-3-5', '1997-3-6', '1997-3-7', '1997-3-8', '1997-3-9', '1997-3-10', '1997-3-11', '1997-3-12', '1997-3-13', '1997-3-14', '1997-3-15', '1997-3-16', '1997-3-17', '1997-3-18', '1997-3-19', '1997-3-20', '1997-3-21', '1997-3-22', '1997-3-23', '1997-3-24', '1997-3-25', '1997-3-26', '1997-3-27', '1997-3-28', '1997-3-29', '1997-3-30', '19

date      0
T_max     0
T_min     0
U_z       0
RH_min    0
RH_max    0
R_n       0
n_sun     0
dtype: int64

In [51]:
!pip install eto
from eto import ETo,datasets

Collecting eto
  Downloading ETo-1.1.0.tar.gz (111 kB)
     |████████████████████████████████| 111 kB 12.6 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from eto) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->eto) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->eto) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->eto) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->eto) (1.15.0)
Building wheels for collected packages: eto
  Building wheel for eto (setup.py) ... done
  Created wheel for eto: filename=ETo-1.1.0-py2.py3-none-any.whl size=113469 sha256=af11e2669a190a8053d57f8ac82e428b9dc42d7b5addeb2dbfb82bc4be410718
  Stored in directory: /root/.cache/pip/wheels/27/3c/85/4cfc3f25ed4adbc404fc676105e52f6840d8c22cb2f28070f0
Successfully built eto
Installing collected packages: eto
Successfully installed eto-1.1.0

In [52]:
Final_data.to_csv('/content/drive/MyDrive/ProfProj/Final_Data.csv')
Final_data = pd.read_csv('/content/drive/MyDrive/ProfProj/Final_Data.csv', parse_dates=True, infer_datetime_format=True, index_col='date')
ET1=ETo()
ET1.param_est(Final_data,freq='D',z_msl=257,lat=30.3398,z_u=2.0)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [53]:
ET1.ts_param.head()
Features=ET1.ts_param
Features=Features[['T_max','T_min','U_z','RH_min','RH_max','R_n','n_sun']]
Features['RH']=(Features['RH_min']+Features['RH_max'])/2
Features=Features.drop(['RH_min','RH_max'],axis=1)
Features.isnull().sum()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

T_max    0
T_min    0
U_z      0
R_n      0
n_sun    0
RH       0
dtype: int64

In [54]:
ETO=ET1.eto_fao()
Output=pd.DataFrame(ETO)
Output=Output.interpolate(method='linear',limit=64)
Output.isnull().sum()

ETo_FAO_mm    0
dtype: int64

In [55]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(Features,Output,test_size=0.3)

In [56]:
from sklearn.utils import validation
RandomForest=RandomForestRegressor()
model=RandomForest.fit(xtrain,ytrain)
result=model.score(xtest,ytest)
print(f"Accuracy: {result*100}")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

Accuracy: 98.54937694187551

In [57]:
#calculating RMLSE r r^2 NSE RAE NRMSE

In [58]:
Features.head()

            T_max  T_min  U_z    R_n  n_sun    RH
date
1993-01-01   20.5   13.5  1.0   6.05    1.6  77.5
1993-01-02   21.3   10.3  2.0   8.96    6.6  84.5
1993-01-03   23.5   11.4  1.0   7.34    2.5  90.0
1993-01-04   20.7    8.4  3.0  11.56    7.8  82.5
1993-01-05   20.7    8.5  7.0   6.83    1.0  81.0

In [59]:
#correlation r
from scipy.stats import spearmanr

In [60]:
Features['T_max'] = Features['T_max'].astype(float)
Output = Output.astype(float)

In [61]:
op=Output['ETo_FAO_mm']
col1=Features['T_max']
corr1,_=spearmanr(col1,op) 
print('Correlation between Output and Max temp ',corr1)
col1=Features['T_max']
corr1=col1. corr(op) 
print('Correlation between Output and Max temp ',corr1)
col1=Features['T_min']
corr1,_=spearmanr(col1,op) 
print('Correlation between Output and Min temp ',corr1)
col1=Features['U_z']
corr1,_=spearmanr(col1,op)  
print('Correlation between Output and wind speed ',corr1)
col1=Features['R_n']
corr1,_=spearmanr(col1,op) 
print('Correlation between Output and Radiations ',corr1)  #Maximum Correlation
col1=Features['n_sun']
corr1,_=spearmanr(col1,op) 
print('Correlation between Output and sunshine hours ',corr1)
col1=Features['RH']
corr1,_=spearmanr(col1,op)  
print('Correlation between Output and Humidity ',corr1)
#lekin inki p value bhi nikaalni hai .......  :(

Correlation between Output and Max temp  0.8208719960765867
Correlation between Output and Max temp  0.7954436235790471
Correlation between Output and Min temp  0.6528050753021766
Correlation between Output and wind speed  0.3167322111634913
Correlation between Output and Radiations  0.9108994704233339
Correlation between Output and sunshine hours  0.5297834724963952
Correlation between Output and Humidity  -0.7546190243144665

In [62]:
# Calculating r2 score
from sklearn.metrics import r2_score
ypred=model.predict(xtest)
r2_score(ytest,ypred)

0.9854937694187551

In [63]:
#calculating RMLSE Root Mean Squared Logarithmic Error used when numbers are too large..else RMSE or standard deviation and RMLSE are nearly same
from sklearn.metrics import mean_squared_log_error
mean_squared_log_error(ytest, ypred)

0.003244562324512705

In [64]:
# calculating NSE Nash–Sutcliffe model efficiency coefficient use to access skills of models
ypred=pd.DataFrame(ypred)
ytest=pd.DataFrame(ytest)
def nse(predictions, targets):
  num=0
  denom=0
  for i in range(len(ypred)):
    num=num+(ypred.iloc[i][0]-ytest.iloc[i][0])**2
    denom=denom+(ypred.iloc[i][0]-np.mean(ypred))**2
  return(1-num/denom)
nse(ypred,ytest)

0    0.984841
dtype: float64

In [65]:
#calculating RAE Relative Absolute Error
import math
ypred=pd.DataFrame(ypred)
ytest=pd.DataFrame(ytest)
def rae(predictions, targets):
  num=0
  denom=0
  for i in range(len(ypred)):
    num=num+(ypred.iloc[i][0]-ytest.iloc[i][0])**2
    denom=denom+(ytest.iloc[i][0])**2
  math.sqrt(num)
  math.sqrt(denom)
  return(1-num/denom)
rae(ypred,ytest)

0.9968038953098283

In [66]:
# calculating NRMSE Normalized root mean square error

In [67]:
Features.shape

(3638, 6)

In [68]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
model=Sequential()

In [69]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(Features,Output,test_size=0.3)

In [70]:
xtrain=xtrain.to_numpy()
xtest=xtest.to_numpy()
ytrain=ytrain.to_numpy()
ytest=ytest.to_numpy()

In [71]:
model.add(Dense(250,activation='relu',input_dim=6))
model.add(Dense(500,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(250,activation='relu'))
model.add(Dense(1,activation='linear'))

In [72]:
import tensorflow as tf
model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3))
model.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
80/80 [==============================] - 5s 13ms/step - loss: 5.8221
Epoch 2/100
80/80 [==============================] - 1s 13ms/step - loss: 0.5015
Epoch 3/100
80/80 [==============================] - 1s 13ms/step - loss: 0.3717
Epoch 4/100
80/80 [==============================] - 1s 14ms/step - loss: 0.3620
Epoch 5/100
80/80 [==============================] - 1s 14ms/step - loss: 0.3958
Epoch 6/100
80/80 [==============================] - 1s 16ms/step - loss: 0.6904
Epoch 7/100
80/80 [==============================] - 1s 14ms/step - loss: 0.3063
Epoch 8/100
80/80 [==============================] - 1s 15ms/step - loss: 0.3238
Epoch 9/100
80/80 [==============================] - 1s 13ms/step - loss: 0.2297
Epoch 10/100
80/80 [==============================] - 1s 12ms/step - loss: 0.3456
Epoch 11/100
80/80 [==============================] - 1s 13ms/step - loss: 0.4962
Epoch 12/100
80/80 [==============================] - 1s 17ms/step - loss: 0.3809
Epoch 13/100
80/80 [==============================] - 1s 13ms/step - loss: 0.2227
Epoch 14/100
80/80 [==============================] - 1s 15ms/step - loss: 0.2023
Epoch 15/100
80/80 [==============================] - 1s 13ms/step - loss: 0.2836
Epoch 16/100
80/80 [==============================] - 1s 15ms/step - loss: 0.2891
Epoch 17/100
80/80 [==============================] - 1s 13ms/step - loss: 0.2603
Epoch 18/100
80/80 [==============================] - 1s 13ms/step - loss: 0.3350
Epoch 19/100
80/80 [==============================] - 1s 13ms/step - loss: 0.9697
Epoch 20/100
80/80 [==============================] - 1s 14ms/step - loss: 0.2304
Epoch 21/100
80/80 [==============================] - 1s 13ms/step - loss: 0.1834
Epoch 22/100
80/80 [==============================] - 1s 12ms/step - loss: 0.1847
Epoch 23/100
80/80 [==============================] - 1s 13ms/step - loss: 0.1546
Epoch 24/100
80/80 [==============================] - 1s 13ms/step - loss: 0.2621
Epoch 25/100
80/80 [==============================] - 1s 13ms/step - loss: 0.1753
Epoch 26/100
80/80 [==============================] - 1s 11ms/step - loss: 0.1690
Epoch 27/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1643
Epoch 28/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2571
Epoch 29/100
80/80 [==============================] - 1s 9ms/step - loss: 0.3532
Epoch 30/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1871
Epoch 31/100
80/80 [==============================] - 1s 9ms/step - loss: 0.3767
Epoch 32/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1373
Epoch 33/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1611
Epoch 34/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1895
Epoch 35/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2190
Epoch 36/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2837
Epoch 37/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1674
Epoch 38/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2794
Epoch 39/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2408
Epoch 40/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2211
Epoch 41/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1393
Epoch 42/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1531
Epoch 43/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1695
Epoch 44/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2605
Epoch 45/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1662
Epoch 46/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1746
Epoch 47/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1683
Epoch 48/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1785
Epoch 49/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1497
Epoch 50/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1411
Epoch 51/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1759
Epoch 52/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1818
Epoch 53/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1549
Epoch 54/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1320
Epoch 55/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1562
Epoch 56/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1416
Epoch 57/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2896
Epoch 58/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1532
Epoch 59/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2123
Epoch 60/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1564
Epoch 61/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1880
Epoch 62/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1298
Epoch 63/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1624
Epoch 64/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1261
Epoch 65/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1468
Epoch 66/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1592
Epoch 67/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2430
Epoch 68/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1780
Epoch 69/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1357
Epoch 70/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1477
Epoch 71/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1164
Epoch 72/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1183
Epoch 73/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1379
Epoch 74/100
80/80 [==============================] - 1s 9ms/step - loss: 0.2112
Epoch 75/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1885
Epoch 76/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1397
Epoch 77/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1677
Epoch 78/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1897
Epoch 79/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1287
Epoch 80/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1194
Epoch 81/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1181
Epoch 82/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1272
Epoch 83/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1195
Epoch 84/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1467
Epoch 85/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1161
Epoch 86/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1308
Epoch 87/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1694
Epoch 88/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1203
Epoch 89/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1528
Epoch 90/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1615
Epoch 91/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1423
Epoch 92/100
80/80 [==============================] - 1s 9ms/step - loss: 0.0980
Epoch 93/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1376
Epoch 94/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1324
Epoch 95/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1492
Epoch 96/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1536
Epoch 97/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1173
Epoch 98/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1095
Epoch 99/100
80/80 [==============================] - 1s 10ms/step - loss: 0.1185
Epoch 100/100
80/80 [==============================] - 1s 9ms/step - loss: 0.1086

In [73]:
from sklearn.metrics import r2_score
ypred=model.predict(xtest)
r2_score(ytest,ypred)

0.9913474856025568

In [74]:
#training model using gradeint boosting algorithm

In [75]:
from sklearn.ensemble import GradientBoostingRegressor 
#finding the best estimator using GridSearchCV
from sklearn.model_selection import GridSearchCV

In [76]:
GB=GradientBoostingRegressor()
paramas={'n_estimators':range(1,100)}
grid=GridSearchCV( estimator=GB,param_grid=paramas,scoring='neg_mean_squared_error')

In [77]:
grid.fit(xtest,ytest)
print(grid.best_estimator_)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GradientBoostingRegressor(n_estimators=99)

In [78]:
print(grid.best_estimator_)

GradientBoostingRegressor(n_estimators=99)

In [79]:
model=grid.best_estimator_
ypred=model.predict(xtest)
r2_score(ytest,ypred)

0.994316430371363

In [80]:
mean_squared_log_error(ytest, ypred)

0.001386807091988718

In [81]:
ypred=pd.DataFrame(ypred)
ytest=pd.DataFrame(ytest)

In [82]:
nse(ypred,ytest)

0    0.99425
dtype: float64

In [83]:
rae(ypred,ytest)

0.9986901554019852

In [99]:
#training model using GLM (elastic net regression)
from sklearn.linear_model import ElasticNet
GLM_model=ElasticNet(alpha=0.4,l1_ratio=0.7)

In [100]:
GLM_model.fit(xtrain,ytrain)
ypred=GLM_model.predict(xtest)

In [101]:
r2_score(ytest,ypred)

0.951820714613963

In [87]:
mean_squared_log_error(ytest, ypred) #error theek kaise kare

ValueError: ignored

In [88]:
ypred=pd.DataFrame(ypred)
ytest=pd.DataFrame(ytest)
nse(ypred,ytest)

0    0.940525
dtype: float64

In [89]:
rae(ypred,ytest)

0.9880357955367951